### ISSUE TITLE
Demo remarks/bugs

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#48]
- [x] Email/phone/address not taken from IYO in "order node" flow
- [ ] Android: remove "Group chat" title, only show topic
- [x] TOS msg doesn't appear in the message inbox, only in the service inbox #49
- [ ] Add thumbs up icon in the Roger that button --> https://github.com/rogerthat-platform/rogerthat-android-client/issues/226 & https://github.com/rogerthat-platform/rogerthat-ios-client/issues/144
- [ ] Add checkbox for non-US citizen message (with js validation, checkbox must be selected) #50
- [ ] Show only the currency in ITO flow, remove the rate #51
- [ ] Don't show amount of tokens in confirmation message. Pierre will formulate the message #51
- [ ] TODO at the end of ITO flow #52
- [ ] Geert was not in hoster/investor role after signing docs #53
- [ ] Remove the call button #54
- [x] iOS --> token transfer keeps spinning
- [ ] Check Stripe? and it's KYC?
